// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Worker.Data;

#nullable disable

namespace UserService.Worker.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20250528220126_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.Worker.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9a64b46-2633-4ac1-8a5b-0bb1fd6d64ef"),
                            CreatedAt = new DateTime(2025, 5, 28, 22, 1, 26, 76, DateTimeKind.Utc).AddTicks(4908),
                            Email = "alice@example.com",
                            Name = "Alice",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("8ad503c2-b7b4-4b32-90a5-ecb0fc734d89"),
                            CreatedAt = new DateTime(2025, 5, 28, 22, 1, 26, 76, DateTimeKind.Utc).AddTicks(4912),
                            Email = "bob@example.com",
                            Name = "Bob",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("a2d1e9e9-89b6-40c8-a66e-5417c92fdd63"),
                            CreatedAt = new DateTime(2025, 5, 28, 22, 1, 26, 76, DateTimeKind.Utc).AddTicks(4914),
                            Email = "carol@example.com",
                            Name = "Carol",
                            Role = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
