services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./init-db:/docker-entrypoint-initdb.d

    identityservice:
        build:
            context: .
            dockerfile: IdentityService.Api/Dockerfile
        depends_on:
            - rabbitmq
            - postgres
        ports:
            - "7000:80"
        environment:
            - ASPNETCORE_HTTP_PORTS=80

    usergatewayapi:
        build:
            context: .
            dockerfile: UserGateway.Api/Dockerfile
        depends_on:
            - rabbitmq
            - postgres
        ports:
            - "5000:80"
        environment:
            - ASPNETCORE_HTTP_PORTS=80

    userserviceworker:
        build:
            context: .
            dockerfile: UserService.Worker/Dockerfile
        depends_on:
            - rabbitmq
            - postgres

volumes:
  pgdata: